version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
